### ISSUE TITLE
执行 python setup.py install 时报错

### ISSUE THREAD

**Issue by Carloslius** [JonathonLuiten/diff-gaussian-rasterization-w-depth#6]
(splatam) root@carlos:/SplaTAM/diff-gaussian-rasterization-w-depth.git# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    from torch.utils.cpp_extension import CUDAExtension, BuildExtension
  File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 191, in <module>
    _load_global_deps()
  File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 153, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/hpcx/ompi/lib/libmpi.so.40: undefined symbol: opal_hwloc201_hwloc_get_type_depth

**Comment by ryoppippi** [comment]
I'm facing a similar error.

```
(splatam) root@rkmtlab-UA9C-R49:/SplaTAM/diff-gaussian-rasterization-w-depth# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    from torch.utils.cpp_extension import CUDAExtension, BuildExtension
  File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 191, in <module>
    _load_global_deps()
  File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 153, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
```

**Comment by ian-pge** [comment]
Hello,
Faced the same problem.
Adding

```
PATH="${PATH}:/opt/hpcx/ompi/bin"
LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/hpcx/ompi/lib"
```

before installing libboost-all-dev in my Dockerfile fixed the issue for me.
